APP_ENV=production
LOG_LEVEL=INFO

# Exchanges
EXCHANGES=bybit,okx,kucoin
PAIRS=BTC/USDT,ETH/USDT,SOL/USDT,BNB/USDT,XRP/USDT,ADA/USDT,DOGE/USDT,AVAX/USDT,MATIC/USDT,DOT/USDT,LTC/USDT,TRX/USDT,ATOM/USDT,LINK/USDT,ETC/USDT,NEAR/USDT,UNI/USDT,APT/USDT,OP/USDT,ARB/USDT
SCAN_INTERVAL_SECONDS=25
ORDERBOOK_TTL_SECONDS=5

# Telegram
TELEGRAM_BOT_TOKEN=change_me
TELEGRAM_CHAT_ID=123456
TELEGRAM_ALLOWED_BOT_ID=123456

# Thresholds
MIN_SPREAD_PCT=0.3

# Redis
REDIS_URL=redis://redis:6379/0

# Postgres
DATABASE_URL=postgresql+psycopg2://arb:arb@postgres:5432/arb

# Dashboard
DASHBOARD_PORT=8000
